var SUITE_TESTES = [
  { categoria_esperada: "motor_eletrico", texto: "Motor WEG 40 CV 380 V 1760 RPM carcaça 200M ano 2018", campos_esperados: {"potencia_cv": 40, "fabricante": "WEG", "rpm": 1760, "tensao_v": 380, "carcaca": "200M", "ano": 2018} },
  { categoria_esperada: "motorredutor", texto: "Motorredutor SEW 5 CV relação 1:20 220/380V", campos_esperados: {"potencia_cv": 5, "fabricante": "SEW-EURODRIVE"} },
  { categoria_esperada: "redutor", texto: "Redutor de velocidade Falk relação 1:40 sem motor", campos_esperados: {"fabricante": null} },
  { categoria_esperada: "bomba", texto: "Bomba centrífuga KSB Meganorm 65-200 vazão 80 m3/h pressão 40 mca", campos_esperados: {"vazao_m3h": 80, "pressao_mca": 40, "fabricante": "KSB"} },
  { categoria_esperada: "trocador_calor", texto: "Trocador de placas Alfa Laval 120 placas inox 316 pressão 10 bar", campos_esperados: {"num_placas_ou_area": 120, "fabricante": "ALFA LAVAL"} },
  { categoria_esperada: "tanque", texto: "Tanque inox 316 volume 10.000 L fabricante Sattva", campos_esperados: {"volume_l": 10000} },
  { categoria_esperada: "tanque_misturador", texto: "Tanque com agitador 5000L inox 304 potência do agitador 10 CV", campos_esperados: {"volume_l": 5000, "potencia_agitador_cv": 10} },
  { categoria_esperada: "reator", texto: "Reator químico 2000L pressão de projeto 15 bar aço carbono", campos_esperados: {"volume_l": 2000, "pressao_projeto_bar": 15} },
  { categoria_esperada: "vaso_pressao", texto: "Vaso de pressão vertical 500L pressão 12 bar aço carbono TUV", campos_esperados: {"volume_l": 500, "pressao_projeto_bar": 12} },
  { categoria_esperada: "silo", texto: "Silo metálico para grãos capacidade 200 toneladas", campos_esperados: {"capacidade_ton": 200} },
  { categoria_esperada: "envasadora", texto: "Envasadora automática capacidade 12.000 unid/h", campos_esperados: {"capacidade_bph": 12000} },
  { categoria_esperada: "linha_envase", texto: "Linha de envase completa Krones 15.000 bph ano 2015", campos_esperados: {"capacidade_bph": 15000, "fabricante": null} },
  { categoria_esperada: "sopradora", texto: "Sopradora PET Sidel 8 cavidades capacidade 10.000 unid/h", campos_esperados: {"num_cavidades": 8, "capacidade_bph": 10000, "fabricante": "SIDEL"} },
  { categoria_esperada: "rotuladora", texto: "Rotuladora automática KHS capacidade 20.000 unid/h rótulo autoadesivo", campos_esperados: {"capacidade_bph": 20000} },
  { categoria_esperada: "tampadora", texto: "Tampadora Krones capacidade 15.000 unid/h tampa rosca", campos_esperados: {"capacidade_bph": 15000} },
  { categoria_esperada: "seladora", texto: "Seladora de embalagens Multivac largura 400mm", campos_esperados: {} },
  { categoria_esperada: "empacotadora", texto: "Empacotadora automática Bosch capacidade 3000 unid/h embalagem flowpack", campos_esperados: {"capacidade_bph": 3000, "fabricante": "BOSCH"} },
  { categoria_esperada: "paletizador", texto: "Paletizadora ABB robótica 60 paletes/h altura máxima 2,2m", campos_esperados: {"capacidade_paletes_hora": 60, "fabricante": "ABB"} },
  { categoria_esperada: "compressor", texto: "Compressor de parafuso Atlas Copco 15 m3/min pressão 8 bar", campos_esperados: {"vazao_m3min": 15, "pressao_bar": 8, "fabricante": "Atlas Copco"} },
  { categoria_esperada: "caldeira", texto: "Caldeira flamotubular a gás 3000 kg/h vapor pressão 10 bar", campos_esperados: {"capacidade_producao_vapor_kgh": 3000} },
  { categoria_esperada: "chiller", texto: "Chiller industrial 200 TR Carrier", campos_esperados: {"capacidade_tr": 200} },
  { categoria_esperada: "torre_resfriamento", texto: "Torre de resfriamento 500 TR fibra de vidro", campos_esperados: {"capacidade_tr": 500} },
  { categoria_esperada: "hvac", texto: "Ar condicionado central VRF 60000 BTU", campos_esperados: {"capacidade_tr_ou_btu": 60000} },
  { categoria_esperada: "transformador", texto: "Transformador trifásico 500 kVA 13800/380V a óleo", campos_esperados: {"potencia_kva": 500, "tensao_primaria_v": 13800, "tensao_secundaria_v": 380} },
  { categoria_esperada: "painel_eletrico", texto: "Painel elétrico CCM 380V 20 circuitos", campos_esperados: {"tensao_v": 380, "num_circuitos": 20} },
  { categoria_esperada: "gerador", texto: "Gerador a diesel 300 kVA Stemac", campos_esperados: {"potencia_kva": 300} },
  { categoria_esperada: "clp", texto: "CLP Siemens S7-1500 32 entradas", campos_esperados: {"fabricante": "SIEMENS"} },
  { categoria_esperada: "inversor", texto: "Inversor de frequência WEG CFW11 50 CV 380V", campos_esperados: {"potencia_cv": 50, "tensao_v": 380, "fabricante": "WEG"} },
  { categoria_esperada: "religadora", texto: "Religadora 15kV 400A", campos_esperados: {"tensao_kv": 15, "corrente_a": 400} },
  { categoria_esperada: "empilhadeira", texto: "Empilhadeira Hyster 2500 kg GLP", campos_esperados: {"capacidade_carga_kg": 2500} },
  { categoria_esperada: "ponte_rolante", texto: "Ponte rolante biviga 10 toneladas vão 15m Demag", campos_esperados: {"capacidade_carga_ton": 10, "fabricante": "DEMAG"} },
  { categoria_esperada: "talha", texto: "Talha elétrica 2 toneladas CM", campos_esperados: {"capacidade_carga_ton": 2} },
  { categoria_esperada: "esteira_transportadora", texto: "Esteira transportadora 20 metros largura 800mm", campos_esperados: {"largura_mm": 800} },
  { categoria_esperada: "elevador_graos", texto: "Elevador de canecas 50 ton/h altura 12m", campos_esperados: {"capacidade_ton_h": 50, "altura_m": 12} },
  { categoria_esperada: "torno", texto: "Torno mecânico Romi 2000mm entre pontas diâmetro 500mm", campos_esperados: {"distancia_pontas_mm": 2000, "diametro_admissivel_mm": 500} },
  { categoria_esperada: "fresadora", texto: "Fresadora universal curso 800x400mm", campos_esperados: {"curso_x_mm": 800, "curso_y_mm": 400} },
  { categoria_esperada: "centro_usinagem_cnc", texto: "Centro de usinagem CNC 5 eixos Romi comando Fanuc", campos_esperados: {"fabricante": "ROMI"} },
  { categoria_esperada: "maquina_solda", texto: "Máquina de solda MIG 300A Lincoln Electric", campos_esperados: {"corrente_max_a": 300, "fabricante": "LINCOLN ELECTRIC"} },
  { categoria_esperada: "retifica", texto: "Retífica cilíndrica curso 1000mm Studer", campos_esperados: {"curso_mm": 1000} },
  { categoria_esperada: "prensa", texto: "Prensa hidráulica 200 toneladas curso 500mm", campos_esperados: {"capacidade_toneladas": 200, "curso_mm": 500} },
  { categoria_esperada: "guilhotina", texto: "Guilhotina hidráulica 3000mm espessura 6mm", campos_esperados: {"comprimento_corte_mm": 3000, "espessura_max_mm": 6} },
  { categoria_esperada: "dobradeira", texto: "Dobradeira CNC 3000mm 100 toneladas", campos_esperados: {"comprimento_dobra_mm": 3000, "capacidade_toneladas": 100} },
  { categoria_esperada: "injetora", texto: "Injetora de plástico 500 toneladas capacidade 800g", campos_esperados: {"forca_fechamento_ton": 500, "capacidade_injecao_g": 800} },
  { categoria_esperada: "caminhao", texto: "Caminhão Mercedes Benz truck baú 12 toneladas ano 2018", campos_esperados: {"capacidade_carga_ton": 12, "ano": 2018} },
  { categoria_esperada: "carreta", texto: "Carreta graneleira 3 eixos Randon", campos_esperados: {} },
  { categoria_esperada: "veiculo_leve", texto: "Veículo utilitário Fiat Fiorino ano 2020", campos_esperados: {"ano": 2020} },
  { categoria_esperada: "terreno", texto: "Terreno industrial 5.000 m2 zoneamento ZUP Campinas/SP", campos_esperados: {"area_total_m2": 5000} },
  { categoria_esperada: "galpao", texto: "Galpão industrial 2.000 m2 pé direito 8 metros Sumaré/SP", campos_esperados: {"area_construida_m2": 2000, "pe_direito_m": 8} },
  { categoria_esperada: "predio_administrativo", texto: "Prédio administrativo 800 m2 3 pavimentos centro de Campinas", campos_esperados: {"area_construida_m2": 800, "num_pavimentos": 3} },
  { categoria_esperada: "planta_industrial", texto: "Planta industrial completa 10.000 m2 de terreno 4.500 m2 construídos", campos_esperados: {"area_terreno_m2": 10000, "area_construida_m2": 4500} },
  { categoria_esperada: "peca_acessorio_maquina", texto: "Placa de identificação para torno Romi", campos_esperados: {} },
  { categoria_esperada: "pasteurizador", texto: "Pasteurizador de placas Tambflex capacidade 5.000 L/h tipo HTST inox 316 ano 2016", campos_esperados: {"capacidade_lh": 5000, "tipo": null} },
  { categoria_esperada: "homogeneizador", texto: "Homogeneizador de alta pressão GEA capacidade 3.000 L/h pressão 250 bar", campos_esperados: {"capacidade_lh": 3000, "pressao_bar": 250} },
  { categoria_esperada: "centrifuga_desnatadeira", texto: "Centrífuga desnatadeira de leite Alfa Laval capacidade 15.000 L/h", campos_esperados: {"capacidade_lh": 15000, "fabricante": "ALFA LAVAL"} },
  { categoria_esperada: "carbonatador", texto: "Carbonatador de bebidas capacidade 8.000 L/h", campos_esperados: {"capacidade_lh": 8000} },
  { categoria_esperada: "resfriador_leite", texto: "Resfriador de leite a granel 5.000 L Fabricante DeLaval", campos_esperados: {"capacidade_l": 5000, "fabricante": "DELAVAL"} },
  { categoria_esperada: "misturador", texto: "Misturador industrial 2000L potência 15 CV", campos_esperados: {"volume_l": 2000, "potencia_cv": 15} },
  { categoria_esperada: "resfriador_garrafas", texto: "Resfriador de garrafas em túnel capacidade 12.000 unid/h", campos_esperados: {"capacidade_bph": 12000} },
  { categoria_esperada: "lavadora_industrial", texto: "Lavadora de garrafas automática capacidade 10.000 unid/h", campos_esperados: {} },
  { categoria_esperada: "envasadora_tribloco", texto: "Enchedora tribloco capacidade 8.000 bph", campos_esperados: {"capacidade_bph": 8000} },
  { categoria_esperada: "envasadora_monobloco", texto: "Enchedora monobloco capacidade 6.000 unid/h", campos_esperados: {"capacidade_bph": 6000} },
  { categoria_esperada: "balanca", texto: "Balança industrial de plataforma capacidade máxima 2000 kg", campos_esperados: {"capacidade_max_kg": 2000} },
  { categoria_esperada: "valvula_industrial", texto: "Válvula borboleta diâmetro 6 polegadas pressão 10 bar aço inox", campos_esperados: {"diametro_pol": 6, "pressao_bar": 10} },
  { categoria_esperada: "filtro_industrial", texto: "Filtro prensa capacidade 50 m3/h", campos_esperados: {} },
  { categoria_esperada: "luminaria_industrial", texto: "Luminária LED industrial 150W", campos_esperados: {"potencia_w": 150} },
  { categoria_esperada: "espectrofotometro", texto: "Espectrofotômetro Shimadzu UV-1800", campos_esperados: {"fabricante": null} },
  { categoria_esperada: "jateamento", texto: "Cabine de jateamento com granalha dimensões 3x3x2,5m", campos_esperados: {} },
  { categoria_esperada: "detector_metais", texto: "Detector de metais industrial esteira 500mm", campos_esperados: {"largura_esteira_mm": 500} },
  { categoria_esperada: "checkweigher", texto: "Balança checadora capacidade máxima 5 kg precisão 1g", campos_esperados: {"capacidade_max_kg": 5} },
  { categoria_esperada: "lavadora_piso", texto: "Lavadora varredora autopropelida bateria", campos_esperados: {} },
  { categoria_esperada: "exaustor", texto: "Exaustor industrial vazão 20.000 m3/h potência 5 CV", campos_esperados: {"vazao_m3h": 20000, "potencia_cv": 5} },
  { categoria_esperada: "forno_industrial", texto: "Forno de secagem a gás capacidade 500 kg temperatura máxima 300°C", campos_esperados: {} },
  { categoria_esperada: "secador_ar", texto: "Secador de ar comprimido refrigerado 20 m3/min", campos_esperados: {"capacidade_m3min": 20} },
  { categoria_esperada: "reservatorio_ar", texto: "Reservatório de ar 2000L pressão máxima 12 bar", campos_esperados: {"volume_l": 2000, "pressao_max_bar": 12} },
  { categoria_esperada: "qgbt", texto: "QGBT quadro geral de baixa tensão 2000A 380V", campos_esperados: {"corrente_a": 2000, "tensao_v": 380} },
  { categoria_esperada: "robo_industrial", texto: "Robô industrial ABB IRB 6700 6 eixos capacidade de carga 200 kg", campos_esperados: {"num_eixos": 6, "capacidade_carga_kg": 200, "fabricante": "ABB"} },
  { categoria_esperada: "unidade_hidraulica", texto: "Unidade hidráulica pressão 200 bar vazão 50 L/min", campos_esperados: {"pressao_bar": 200, "vazao_lmin": 50} },
  { categoria_esperada: "atuador_eletrico", texto: "Atuador elétrico linear curso 300mm", campos_esperados: {} },
  { categoria_esperada: "sucata", texto: "Sucata de aço carbono peso 5 toneladas", campos_esperados: {"tipo_material": null, "peso_ton": 5} },
  { categoria_esperada: "centro_usinagem_cnc", texto: "Centro de usinagem CNC Haas VF-2 curso X 762mm Y 406mm Z 508mm", campos_esperados: {} },
  { categoria_esperada: "instrumentacao", texto: "Transmissor de pressão Rosemount faixa 0-100 bar", campos_esperados: {} },
];
